require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AbastecimentosController do

  # This should return the minimal set of attributes required to create a valid
  # Abastecimento. As you add validations to Abastecimento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "km" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AbastecimentosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all abastecimentos as @abastecimentos" do
      abastecimento = Abastecimento.create! valid_attributes
      get :index, {}, valid_session
      assigns(:abastecimentos).should eq([abastecimento])
    end
  end

  describe "GET show" do
    it "assigns the requested abastecimento as @abastecimento" do
      abastecimento = Abastecimento.create! valid_attributes
      get :show, {:id => abastecimento.to_param}, valid_session
      assigns(:abastecimento).should eq(abastecimento)
    end
  end

  describe "GET new" do
    it "assigns a new abastecimento as @abastecimento" do
      get :new, {}, valid_session
      assigns(:abastecimento).should be_a_new(Abastecimento)
    end
  end

  describe "GET edit" do
    it "assigns the requested abastecimento as @abastecimento" do
      abastecimento = Abastecimento.create! valid_attributes
      get :edit, {:id => abastecimento.to_param}, valid_session
      assigns(:abastecimento).should eq(abastecimento)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Abastecimento" do
        expect {
          post :create, {:abastecimento => valid_attributes}, valid_session
        }.to change(Abastecimento, :count).by(1)
      end

      it "assigns a newly created abastecimento as @abastecimento" do
        post :create, {:abastecimento => valid_attributes}, valid_session
        assigns(:abastecimento).should be_a(Abastecimento)
        assigns(:abastecimento).should be_persisted
      end

      it "redirects to the created abastecimento" do
        post :create, {:abastecimento => valid_attributes}, valid_session
        response.should redirect_to(Abastecimento.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved abastecimento as @abastecimento" do
        # Trigger the behavior that occurs when invalid params are submitted
        Abastecimento.any_instance.stub(:save).and_return(false)
        post :create, {:abastecimento => { "km" => "invalid value" }}, valid_session
        assigns(:abastecimento).should be_a_new(Abastecimento)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Abastecimento.any_instance.stub(:save).and_return(false)
        post :create, {:abastecimento => { "km" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested abastecimento" do
        abastecimento = Abastecimento.create! valid_attributes
        # Assuming there are no other abastecimentos in the database, this
        # specifies that the Abastecimento created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Abastecimento.any_instance.should_receive(:update_attributes).with({ "km" => "MyString" })
        put :update, {:id => abastecimento.to_param, :abastecimento => { "km" => "MyString" }}, valid_session
      end

      it "assigns the requested abastecimento as @abastecimento" do
        abastecimento = Abastecimento.create! valid_attributes
        put :update, {:id => abastecimento.to_param, :abastecimento => valid_attributes}, valid_session
        assigns(:abastecimento).should eq(abastecimento)
      end

      it "redirects to the abastecimento" do
        abastecimento = Abastecimento.create! valid_attributes
        put :update, {:id => abastecimento.to_param, :abastecimento => valid_attributes}, valid_session
        response.should redirect_to(abastecimento)
      end
    end

    describe "with invalid params" do
      it "assigns the abastecimento as @abastecimento" do
        abastecimento = Abastecimento.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Abastecimento.any_instance.stub(:save).and_return(false)
        put :update, {:id => abastecimento.to_param, :abastecimento => { "km" => "invalid value" }}, valid_session
        assigns(:abastecimento).should eq(abastecimento)
      end

      it "re-renders the 'edit' template" do
        abastecimento = Abastecimento.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Abastecimento.any_instance.stub(:save).and_return(false)
        put :update, {:id => abastecimento.to_param, :abastecimento => { "km" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested abastecimento" do
      abastecimento = Abastecimento.create! valid_attributes
      expect {
        delete :destroy, {:id => abastecimento.to_param}, valid_session
      }.to change(Abastecimento, :count).by(-1)
    end

    it "redirects to the abastecimentos list" do
      abastecimento = Abastecimento.create! valid_attributes
      delete :destroy, {:id => abastecimento.to_param}, valid_session
      response.should redirect_to(abastecimentos_url)
    end
  end

end
