require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrganizacaosController do

  # This should return the minimal set of attributes required to create a valid
  # Organizacao. As you add validations to Organizacao, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nome" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrganizacaosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all organizacaos as @organizacaos" do
      organizacao = Organizacao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:organizacaos).should eq([organizacao])
    end
  end

  describe "GET show" do
    it "assigns the requested organizacao as @organizacao" do
      organizacao = Organizacao.create! valid_attributes
      get :show, {:id => organizacao.to_param}, valid_session
      assigns(:organizacao).should eq(organizacao)
    end
  end

  describe "GET new" do
    it "assigns a new organizacao as @organizacao" do
      get :new, {}, valid_session
      assigns(:organizacao).should be_a_new(Organizacao)
    end
  end

  describe "GET edit" do
    it "assigns the requested organizacao as @organizacao" do
      organizacao = Organizacao.create! valid_attributes
      get :edit, {:id => organizacao.to_param}, valid_session
      assigns(:organizacao).should eq(organizacao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Organizacao" do
        expect {
          post :create, {:organizacao => valid_attributes}, valid_session
        }.to change(Organizacao, :count).by(1)
      end

      it "assigns a newly created organizacao as @organizacao" do
        post :create, {:organizacao => valid_attributes}, valid_session
        assigns(:organizacao).should be_a(Organizacao)
        assigns(:organizacao).should be_persisted
      end

      it "redirects to the created organizacao" do
        post :create, {:organizacao => valid_attributes}, valid_session
        response.should redirect_to(Organizacao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved organizacao as @organizacao" do
        # Trigger the behavior that occurs when invalid params are submitted
        Organizacao.any_instance.stub(:save).and_return(false)
        post :create, {:organizacao => { "nome" => "invalid value" }}, valid_session
        assigns(:organizacao).should be_a_new(Organizacao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Organizacao.any_instance.stub(:save).and_return(false)
        post :create, {:organizacao => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested organizacao" do
        organizacao = Organizacao.create! valid_attributes
        # Assuming there are no other organizacaos in the database, this
        # specifies that the Organizacao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Organizacao.any_instance.should_receive(:update_attributes).with({ "nome" => "MyString" })
        put :update, {:id => organizacao.to_param, :organizacao => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested organizacao as @organizacao" do
        organizacao = Organizacao.create! valid_attributes
        put :update, {:id => organizacao.to_param, :organizacao => valid_attributes}, valid_session
        assigns(:organizacao).should eq(organizacao)
      end

      it "redirects to the organizacao" do
        organizacao = Organizacao.create! valid_attributes
        put :update, {:id => organizacao.to_param, :organizacao => valid_attributes}, valid_session
        response.should redirect_to(organizacao)
      end
    end

    describe "with invalid params" do
      it "assigns the organizacao as @organizacao" do
        organizacao = Organizacao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Organizacao.any_instance.stub(:save).and_return(false)
        put :update, {:id => organizacao.to_param, :organizacao => { "nome" => "invalid value" }}, valid_session
        assigns(:organizacao).should eq(organizacao)
      end

      it "re-renders the 'edit' template" do
        organizacao = Organizacao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Organizacao.any_instance.stub(:save).and_return(false)
        put :update, {:id => organizacao.to_param, :organizacao => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested organizacao" do
      organizacao = Organizacao.create! valid_attributes
      expect {
        delete :destroy, {:id => organizacao.to_param}, valid_session
      }.to change(Organizacao, :count).by(-1)
    end

    it "redirects to the organizacaos list" do
      organizacao = Organizacao.create! valid_attributes
      delete :destroy, {:id => organizacao.to_param}, valid_session
      response.should redirect_to(organizacaos_url)
    end
  end

end
